version: '3.7'
services:
  zookeeper:
    image: bitnami/zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
  kafka:
    image: bitnami/kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9991
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9991
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    ports:
      - '9991:9991'
    depends_on:
      - zookeeper
  iddb:
    image: postgres:14-alpine
    ports:
      - '5401:5432'
    volumes:
      - ./id/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    command: [ "postgres", "-c", "log_statement=all" ]
  catalogdb:
    image: postgres:14-alpine
    ports:
      - '5402:5432'
    volumes:
      - ./catalog/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    command: [ "postgres", "-c", "log_statement=all" ]
  plannerdb:
    image: postgres:14-alpine
    ports:
      - '5403:5432'
    volumes:
      - ./planner/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    command: [ "postgres", "-c", "log_statement=all" ]
  ordersdb:
    image: postgres:14-alpine
    ports:
      - '5404:5432'
    volumes:
      - ./orders/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    command: [ "postgres", "-c", "log_statement=all" ]
  messagedb:
    image: postgres:14-alpine
    ports:
      - '5405:5432'
    volumes:
      - ./message/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    command: [ "postgres", "-c", "log_statement=all" ]
  bonusdb:
    image: postgres:14-alpine
    ports:
      - '5406:5432'
    volumes:
      - ./bonus/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    command: [ "postgres", "-c", "log_statement=all" ]
